#!/bin/bash

count=-1
sum=0
a=0
b="s"
echo $b
while [ $a != $b ]
do
read a
echo $a

		sum=$((sum+a))
		count=$((count + 1))
	done
echo "Sum=$sum"
echo "Count=$count"
avg=$(echo "scale=2;$sum/$count" | bc)
echo "Average=" $avg
